# numpy
- 데이터프레임은 테이블 구조의 데이터를 편리하게 조작하기 위해서 사용한다
- 숫자만으로 구성된 데이터를 대상으로 "연산"을 하기 위해서는 배열 (array) 형태여야  한다
- 이를 위해 넘파이 라이브러리를 사용한다
 - 다 차원 배열 ndarray(n-dimensional array)를 다룬다

## 리스트/데이터프레임과 배열의 차이
- 리스트는 데이터를 "목록"으로 만들거나 조작하는 용도 (추가, 삭제, 변형 등)
- 데이터프레임은 2차원 테이블 구조의 데이터를 만들고, 조작하는 용도
- 배열은 연산을 위해, 숫자만으로 구성된, 수학의 매트릭스와 같은 용도

## 코랩에 한글 폰트 설치
- (주의!) 아래 셀을 실행 후에, 런타임 - 런타임 다시 시작을 수행해야 한다
 - 코랩은 리눅스 머신이면 한글이 미리 설치되어 있지 않다
 - 한글이 이미 설치된 PC에서는 아래 셀을 실행할 필요없다

In [ ]:
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

# 런타임 - 런타임 다시시작 수행

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  fonts-nanum
0 upgraded, 1 newly installed, 0 to remove and 38 not upgraded.
Need to get 9,599 kB of archives.
After this operation, 29.6 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal/universe amd64 fonts-nanum all 20180306-3 [9,599 kB]
Fetched 9,599 kB in 1s (10.7 MB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Selecting previously unselected package fonts-nanum.
(Reading database ... 122541 files and dir

## 한글 사용 설정
- 그림에 한글이 보이게 하기 위해서 한글 사용을 설정한다.
- 운영체제마다 명령이 다르다

In [ ]:
import platform, matplotlib
from matplotlib import rc
import matplotlib.pyplot as plt 

# '-' 기호 제대로 보이기
matplotlib.rcParams['axes.unicode_minus'] = False

# 한글 폰트 불러오기
# 윈도우
if platform.system() == 'Windows':
    rc('font', family="Malgun Gothic")
# 맥
elif platform.system() == 'Darwin':
    rc('font', family='AppleGothic')
# 리눅스
elif platform.system() == 'Linux':
    plt.rcParams['font.family'] = 'NanumBarunGothic' 

## import


In [4]:
import pandas as pd

# 리스트와 어레이

## 리스트 조작

In [6]:
## 리스트의 복제(*)와 어레이의 곱셈 비교

import numpy as np

x = [1, 2, 5,10]  # 리스트 생성
print(x*3)

y = np.array(x) # 리스트를 어레이로 변환
print(y*3)

[1, 2, 5, 10, 1, 2, 5, 10, 1, 2, 5, 10]
[ 3  6 15 30]


In [7]:
## 어레이를 리스트로 바꾸고 타입 확인하기

z = list(y)     # 어레이를 리스트로 타입을 바꾼다
print(z)        # [1, 2, 5, 10]
print(type(y))  # class 'numpy.ndarray'>
print(type(z))  # <class 'list'>

[1, 2, 5, 10]
<class 'numpy.ndarray'>
<class 'list'>


In [9]:
## 어레이의 연산은 각 항목별로 수행된다

y1 = np.array([1, 2, 3, 4])
y2 = np.array([10, 10, 100, 100])

print(y1 + y2)  # [ 11  12 103 104]
print(y1 - y2)  # [ -9  -8 -97 -96]
print(y1 * y2)  # [ 10  20 300 400]
print(y1 / y2)  # [0.1  0.2  0.03 0.04]

[ 11  12 103 104]
[ -9  -8 -97 -96]
[ 10  20 300 400]
[0.1  0.2  0.03 0.04]


In [10]:
## 어레이에 단변수의 연산을 수행하기

y1 = np.array([1, 2, 3, 4])
a = 1000

print(y1 + a)  # [1001 1002 1003 1004]
print(y1 - a)  # [-999 -998 -997 -996]
print(y1 * a)  # [1000 2000 3000 4000]
print(y1 / a)  # [0.001 0.002 0.003 0.004]

[1001 1002 1003 1004]
[-999 -998 -997 -996]
[1000 2000 3000 4000]
[0.001 0.002 0.003 0.004]


In [11]:
## 리스트에 대한 + 수행은 두 리스트를 합친다

y1 = np.array([1, 2, 3, 4])
y2 = np.array([10, 10, 100, 100])

list(y1)+list(y2) # [1, 2, 3, 4, 10, 10, 100, 100]

[1, 2, 3, 4, 10, 10, 100, 100]

## arange
- range 타입의 "범위" 데이터를 생성한 후 이를 배열로 만든다

In [12]:
# 일정한 간격의 수로 구성된 어레이를 얻는다

print(np.arange(6))      # [0 1 2 3 4 5]
print(np.arange(1,7))    # [1 2 3 4 5 6]
print(np.arange(1,20,3)) # [ 1  4  7 10 13 16 19]
print(np.arange(1.1,4,0.5))# [1.1 1.6 2.1 2.6 3.1 3.6]

[0 1 2 3 4 5]
[1 2 3 4 5 6]
[ 1  4  7 10 13 16 19]
[1.1 1.6 2.1 2.6 3.1 3.6]


## 데이터프레임과 어레이
- 기본적으로 행단로 추출하며 마치 행 번호를 인덱스인 것처럼 사용

In [13]:
## 임의의 도시정보 데이터프레임을 만드는 예

import pandas as pd

x = {'city': ['서울', '부산', '대구', '대전', '광주'],
     'population': [990, 350, 250, 154, 150],
     'temp': [13, 16, 14, 13, 15],
     'cars': [300, 120, 80, 90, 70]}

df = pd.DataFrame(x)
df.set_index("city", inplace=True)
df

population  temp  cars
city                        
서울           990    13   300
부산           350    16   120
대구           250    14    80
대전           154    13    90
광주           150    15    70

In [14]:
## 데이터프레임을 어레이로 바꾸는 방법

z = df.values
print(z.shape)
z

(5, 3)


array([[990,  13, 300],
       [350,  16, 120],
       [250,  14,  80],
       [154,  13,  90],
       [150,  15,  70]])

In [15]:
list(df.columns)  # 결과: ['population', 'temp', 'cars']
list(df.index) # 결과: ['서울', '부산', '대구', '대전', '광주']

['서울', '부산', '대구', '대전', '광주']

In [14]:
## 어레이는 바로 데이터프레임으로 바꿀 수 있다.

df2 = pd.DataFrame(z)
df2

0   1    2
0  990  13  300
1  350  16  120
2  250  14   80
3  154  13   90
4  150  15   70

In [15]:
## 데이터프레임을 만들면서 인덱스와 컬럼명을 지정

df2 = pd.DataFrame(z, index=df.index, columns=df.columns)
df2

population  temp  cars
city                        
서울           990    13   300
부산           350    16   120
대구           250    14    80
대전           154    13    90
광주           150    15    70

In [16]:
## 어레이의 0~3 사이의 행을 얻기

z[:3]

array([[990,  13, 300],
       [350,  16, 120],
       [250,  14,  80]])

In [17]:
## 모든 행에 대해서, 컬럼 0과 2만 얻기

z[:,[0,2]]

array([[990, 300],
       [350, 120],
       [250,  80],
       [154,  90],
       [150,  70]])

In [16]:
## 임의의 어레이 두개 생성

x1 = np.arange(0,12).reshape(4,3)
x2 = np.arange(100,112).reshape(4,3)

x1, x2

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[100, 101, 102],
        [103, 104, 105],
        [106, 107, 108],
        [109, 110, 111]]))

In [19]:
## 디폴트는 행 방향 (세로 방향)으로 붙인다

x3 = np.concatenate((x1, x2))
x3


array([[  0,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10,  11],
       [100, 101, 102],
       [103, 104, 105],
       [106, 107, 108],
       [109, 110, 111]])

In [20]:
## 컬럼 방향으로 붙이기 (axis=1)

x3 = np.concatenate((x1, x2), axis=1)
x3

array([[  0,   1,   2, 100, 101, 102],
       [  3,   4,   5, 103, 104, 105],
       [  6,   7,   8, 106, 107, 108],
       [  9,  10,  11, 109, 110, 111]])

In [20]:
## 어레이를 csv 파일로 저장한 후 파일 읽기

x = np.arange(48).reshape(6,8)
print(x)
np.savetxt('big.csv', x, fmt='%d', delimiter=',')

with open('big.csv') as f: 
    print(f.read())

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]]
0,1,2,3,4,5,6,7
8,9,10,11,12,13,14,15
16,17,18,19,20,21,22,23
24,25,26,27,28,29,30,31
32,33,34,35,36,37,38,39
40,41,42,43,44,45,46,47



In [22]:
## csv 파일의 내용을 어레이로 바로 읽기

y = np.loadtxt('big.csv', delimiter=',')
y

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29., 30., 31.],
       [32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47.]])