# 파일 다루기
- 파일 열기 open(), with로 열기
- csv, xlsx 파일 다루기
- zip 파일 다루기
- 폴더 내 파일 목록 다루기 (glob, listdir)
- 폴더/파일 생성과 삭제

## import

In [1]:
import pandas as pd
import numpy as np
from numpy.random import rand
import csv
import os
from glob import glob

##  데이터  생성과 저장하기
- 숫자 데이터를 생성하고 csv 파일로 저장하기

In [2]:
## 0~1 사이의 랜덤 넘버 10개를 만들고 csv 파일에 저장하고 확인하기

import numpy as np
x1 = np.random.rand(10)
print(type(x1))         # ndarray 타입

np.savetxt("test_1.csv", x1, delimiter=",", fmt = '%.3f')

with open('test_1.csv') as f: 
    contents = f.read()
    print(type(contents))  # str 타입
    print(contents)

<class 'numpy.ndarray'>
<class 'str'>
0.484
0.058
0.927
0.774
0.143
0.056
0.417
0.011
0.844
0.737



- !cat, !type 등 명령어로 직접 보기

In [3]:
!cat test_1.csv # 맥이나 리눅스에서
#!type test_1.csv  # 윈도우에서 

0.484
0.058
0.927
0.774
0.143
0.056
0.417
0.011
0.844
0.737


In [4]:
## csv 파일을 어레이로 읽어서 100을 곱한 값 보기

x = np.loadtxt('test_1.csv', delimiter=',')
print(type(x))    # ndarray 타입
print(x*100)

<class 'numpy.ndarray'>
[48.4  5.8 92.7 77.4 14.3  5.6 41.7  1.1 84.4 73.7]


### 2차원 구조 데이터

In [5]:
## 0~30 로 구성된 (5,6) 구조의 어레이를 csv 파일에 저장하기

x2 = np.arange(30).reshape(5,6)

np.savetxt("test_2.csv", x2, delimiter=",", fmt = '%d')

with open('test_2.csv') as f: 
    contents = f.read()
    print(type(contents))  # str 타입
    print(contents)

<class 'str'>
0,1,2,3,4,5
6,7,8,9,10,11
12,13,14,15,16,17
18,19,20,21,22,23
24,25,26,27,28,29



In [6]:
## 2차원 csv 파일을 어레이로 읽는 예

x = np.loadtxt('test_2.csv', delimiter=',')
print(type(x))
print(x)

<class 'numpy.ndarray'>
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]]


In [7]:
## loadtxt()가 제공하는 읽는 옵션

print('---- 3개의 행만 읽는다 ----')
x = np.loadtxt('test_2.csv', delimiter=',', max_rows=1000)
print(x)

print('\n---- 처음 2개의 행은 읽지 않는다 ----')
x = np.loadtxt('test_2.csv', delimiter=',', skiprows=2)
print(x)

print('\n---- 컬럼을 (0,2,4)만 읽는다 ----')
x = np.loadtxt('test_2.csv', delimiter=',', usecols=(0,2,4))
print(x)

---- 3개의 행만 읽는다 ----
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]]

---- 처음 2개의 행은 읽지 않는다 ----
[[12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]]

---- 컬럼을 (0,2,4)만 읽는다 ----
[[ 0.  2.  4.]
 [ 6.  8. 10.]
 [12. 14. 16.]
 [18. 20. 22.]
 [24. 26. 28.]]


In [8]:
!cat test_2.csv

0,1,2,3,4,5
6,7,8,9,10,11
12,13,14,15,16,17
18,19,20,21,22,23
24,25,26,27,28,29


## 데이터프레임으로 읽기

In [9]:
## 2차원 어레이를 데이터프레임으로 읽기

df = pd.read_csv('test_2.csv')  
df

0   1   2   3   4   5
0   6   7   8   9  10  11
1  12  13  14  15  16  17
2  18  19  20  21  22  23
3  24  25  26  27  28  29

In [10]:
# 어레이로 변환하기
df.values

array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

### read_csv 옵션

- nrows=1000         # 상위 1000줄만 읽기
- skiprows = 3       # 처음 3행 건너뛰기
- skipfooter = 1000 # 맨 뒤의 1000행은 읽지 않기
- usecols= (0,2,4)  # 해당 컬럼만 읽기

In [11]:
# 일부 행만 읽기 nrows 사용 (3줄 읽기)

df2 = pd.read_csv('test_2.csv', nrows=3, header=None)
df2

0   1   2   3   4   5
0   0   1   2   3   4   5
1   6   7   8   9  10  11
2  12  13  14  15  16  17

In [12]:
df2 = pd.read_csv('test_2.csv', skiprows=3, header=None)
df2

0   1   2   3   4   5
0  18  19  20  21  22  23
1  24  25  26  27  28  29

### 액셀 한글 인코딩
- 문자의 인코딩은 기본적으로 utf-8 을 사용한다
- 그러나 한글의 경우 다른 인코딩으로 저장되는 경우가 있다
 - MS 액셀에서 csv로 저장할 때 한글이 cpc949로 인코딩된다. 이때는 아래 옵션이 필요하다
 - encoding = 'cpc949'
 - encoding = 'euc-kr'을 선택해야 하는 경우도 있다

## zip 파일 
### zip 파일 만들기
- output.csv 을 output.zip로 압축하는 경우

In [13]:
!cat test_2.csv

0,1,2,3,4,5
6,7,8,9,10,11
12,13,14,15,16,17
18,19,20,21,22,23
24,25,26,27,28,29


In [14]:
!cat test_1.csv

0.484
0.058
0.927
0.774
0.143
0.056
0.417
0.011
0.844
0.737


In [15]:
## zip 파일로 압축하기

import zipfile
with zipfile.ZipFile('output.zip', 'w') as z:
    z.write('test_1.csv')
    z.write('test_2.csv')

# zip에 포함된 파일명 보기와 압출 풀기

with zipfile.ZipFile("output.zip", 'r') as z: 
    print(z.namelist()) 
    z.extractall() 

['test_1.csv', 'test_2.csv']


- (참고) read_csv에서 zip 파일을 바로 읽을 수 있다 (압축을 풀 필요 없다)

In [16]:
# pd.read_csv('output.zip', header=None)  

# 폴더 작업

## 현재 폴더 위치 보기
- cwd (current working directory)

In [17]:
## 현재 작업중인 폴더 경로 보기

import os
cwd = os.getcwd()
print(cwd)

/Users/hwa-kim/Library/CloudStorage/Dropbox/lab/book12


In [18]:
## 특정 폴더가 없으면 새로 만들기

if not os.path.exists("./data_tmp"):
    os.mkdir("./data_tmp")

## 폴더의 파일 목록 얻기
- glob() 사용: 파일 타입을 지정할 수 있다
- listdir() 사용: 경로를 줄 수 있다

### glob()를 사용

In [19]:
## 현재 폴더의 파일 목록 얻기

from glob import glob
f_list = glob('*')
f_list

['i_11_MachineLearning.ipynb',
 'bb91_47_Constraint.ipynb',
 'bb9_fin_57_Collaborative_Filtering.ipynb',
 'c_22_4_findContour.ipynb',
 'h_02_pandas.ipynb',
 'bb6_MultiOutput.ipynb',
 'features.csv.zip',
 'jump-up-solution-withcode.ipynb',
 'fn_2_walmart-sales-forecast.ipynb',
 'README.roboflow.txt',
 'PRI0830-main',
 'bb6_GD.ipynb',
 'i_7_PublicData.ipynb',
 'bb25_Tables.ipynb',
 'bb92_61_1_물류최적화개념.ipynb',
 'd_03_Numpy.ipynb',
 'df_styled.png',
 'cities.xlsx',
 'f_21_StatisticsBasic.ipynb',
 'c_86_9_GenarativeModel_VAE_Smiles.ipynb',
 'i_6_MachineLearning.ipynb',
 'bb9_71_2_BOW_DTM.ipynb',
 'test_1.csv',
 'e_72_CatDog_Keras.ipynb',
 'e_22_Python.ipynb',
 'video1475379706.mp4',
 'hh_20_앙상블알고리즘.ipynb',
 'c_85_10_drug_molecule_generation_with_vae.ipynb',
 'hh_34_오염예측_LSTM.ipynb',
 'Attendees_0817',
 'c_85_12_GAN_torch.ipynb',
 'c_86_10_GenerativeModel_VAE_Graph.ipynb',
 'e_61_FeatureEngineering.ipynb',
 'h_90_series_clustering.ipynb',
 'A.csv',
 'hh_34_시계열_

In [20]:
sorted(f_list)

['1.pdf',
 '265.pdf',
 '319.pdf',
 '62-1.pdf',
 '84_10_Unsupervised_Embeddings_for_Molecules.ipynb',
 'A.csv',
 'AIDD',
 'AIDD(수정본0712)',
 'AIwithPython-main',
 'ALL.sdf',
 'Attendees_0817',
 'Attendees_0817.csv',
 'Attendees_0817.xlsx',
 'B.csv',
 'C.csv',
 'DS-210905.hwp',
 'DX_Motor.ipynb',
 'DeepLearning101-master',
 'Glycine.mol',
 'LGadd2.zip',
 'Life Expectancy Data.csv',
 'Merged_excel.xlsx',
 'NGdata1.zip',
 'PM_train_pre.csv',
 'PRI0830-main',
 'PRI0830-main.zip',
 'Project_Life_Expectancy.ipynb',
 'Python_ML_220310.hwp',
 'README.dataset.txt',
 'README.roboflow.txt',
 'Refr.csv',
 'S3 사후과제_1차',
 'S3 사후과제_2차',
 'SET_angle_V2.ipynb',
 'SeoulBikeData.csv',
 'Standalone-DeepLearning-Chemistry-2e57d5b4188c7ead90467fc39069f0de47b87931',
 'TV.csv',
 'Team3.ipynb',
 'Test_data.xlsx',
 '__MACOSX',
 'a.sdf',
 'b.mol',
 'b21_Jupyter.ipynb',
 'b22_Python.ipynb',
 'b23_Pandas_Groupby.ipynb',
 'b24_numpy.ipynb',
 'b25_Function.ipynb',
 'b55_DT_RF_Boost-Copy1.ipynb',
 'b56_D

In [21]:
f_list

['i_11_MachineLearning.ipynb',
 'bb91_47_Constraint.ipynb',
 'bb9_fin_57_Collaborative_Filtering.ipynb',
 'c_22_4_findContour.ipynb',
 'h_02_pandas.ipynb',
 'bb6_MultiOutput.ipynb',
 'features.csv.zip',
 'jump-up-solution-withcode.ipynb',
 'fn_2_walmart-sales-forecast.ipynb',
 'README.roboflow.txt',
 'PRI0830-main',
 'bb6_GD.ipynb',
 'i_7_PublicData.ipynb',
 'bb25_Tables.ipynb',
 'bb92_61_1_물류최적화개념.ipynb',
 'd_03_Numpy.ipynb',
 'df_styled.png',
 'cities.xlsx',
 'f_21_StatisticsBasic.ipynb',
 'c_86_9_GenarativeModel_VAE_Smiles.ipynb',
 'i_6_MachineLearning.ipynb',
 'bb9_71_2_BOW_DTM.ipynb',
 'test_1.csv',
 'e_72_CatDog_Keras.ipynb',
 'e_22_Python.ipynb',
 'video1475379706.mp4',
 'hh_20_앙상블알고리즘.ipynb',
 'c_85_10_drug_molecule_generation_with_vae.ipynb',
 'hh_34_오염예측_LSTM.ipynb',
 'Attendees_0817',
 'c_85_12_GAN_torch.ipynb',
 'c_86_10_GenerativeModel_VAE_Graph.ipynb',
 'e_61_FeatureEngineering.ipynb',
 'h_90_series_clustering.ipynb',
 'A.csv',
 'hh_34_시계열_

## listdir() 사용
- 인자에 파일을 찾을 폴더 경로를 지정할 수 있다
- 쓰지 않으면 현재 폴더를 찾는다

In [22]:
os.listdir()

['i_11_MachineLearning.ipynb',
 'bb91_47_Constraint.ipynb',
 'bb9_fin_57_Collaborative_Filtering.ipynb',
 'c_22_4_findContour.ipynb',
 'h_02_pandas.ipynb',
 'bb6_MultiOutput.ipynb',
 'features.csv.zip',
 'jump-up-solution-withcode.ipynb',
 'fn_2_walmart-sales-forecast.ipynb',
 'README.roboflow.txt',
 'PRI0830-main',
 'bb6_GD.ipynb',
 'i_7_PublicData.ipynb',
 'bb25_Tables.ipynb',
 'bb92_61_1_물류최적화개념.ipynb',
 'd_03_Numpy.ipynb',
 'df_styled.png',
 'cities.xlsx',
 'f_21_StatisticsBasic.ipynb',
 'c_86_9_GenarativeModel_VAE_Smiles.ipynb',
 'i_6_MachineLearning.ipynb',
 'bb9_71_2_BOW_DTM.ipynb',
 'test_1.csv',
 'e_72_CatDog_Keras.ipynb',
 'e_22_Python.ipynb',
 'video1475379706.mp4',
 'hh_20_앙상블알고리즘.ipynb',
 'c_85_10_drug_molecule_generation_with_vae.ipynb',
 'hh_34_오염예측_LSTM.ipynb',
 'Attendees_0817',
 'c_85_12_GAN_torch.ipynb',
 'c_86_10_GenerativeModel_VAE_Graph.ipynb',
 'e_61_FeatureEngineering.ipynb',
 'h_90_series_clustering.ipynb',
 'A.csv',
 'hh_34_시계열_

## 기타 폴더 및 파일 관리 함수
- os 패키지에서 제공하는 함수
 - 폴더 생성 mkdir()
 - 폴더 위치 이동 chdir()
 - 파일 이름 변경 rename()
 - 파일 삭제 remove()
 - 폴더 삭제 rmdir()